# Generated by Django 3.2.7 on 2022-05-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='room_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a101', models.BooleanField(default=False, verbose_name='101')),
                ('a102', models.BooleanField(default=False, verbose_name='101')),
            ],
        ),
    ]
