# Generated by Django 3.2.7 on 2022-05-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_book',
            name='a103',
            field=models.BooleanField(default=False, verbose_name='103'),
        ),
        migrations.AddField(
            model_name='room_book',
            name='a104',
            field=models.BooleanField(default=False, verbose_name='104'),
        ),
        migrations.AddField(
            model_name='room_book',
            name='a105',
            field=models.BooleanField(default=False, verbose_name='105'),
        ),
        migrations.AddField(
            model_name='room_book',
            name='a106',
            field=models.BooleanField(default=False, verbose_name='106'),
        ),
        migrations.AddField(
            model_name='room_book',
            name='a107',
            field=models.BooleanField(default=False, verbose_name='107'),
        ),
        migrations.AddField(
            model_name='room_book',
            name='a108',
            field=models.BooleanField(default=False, verbose_name='108'),
        ),
        migrations.AlterField(
            model_name='room_book',
            name='a102',
            field=models.BooleanField(default=False, verbose_name='102'),
        ),
    ]
